"""added new link for hotel

Revision ID: f3fa05e5922d
Revises: 5737b5298a38
Create Date: 2026-05-11 18:01:17.185378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fa05e5922d'
down_revision = '5737b5298a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maps_link', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('booking_link', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('booking_link')
        batch_op.drop_column('maps_link')

    # ### end Alembic commands ###
